interface data {
    APP_GESTORSHORTS_SOCIALNETWORK_PORT: number,
    APP_GESTORSHORTS_SOCIALNETWORK_GETALLSHORTS: string,
    APP_GESTORSHORTS_SOCIALNETWORK_GETONESHORT: string,
    APP_GESTORSHORTS_SOCIALNETWORK_GET_SHORTBYUSER: string,
    APP_GESTORSHORTS_SOCIALNETWORK_POST_SAVESHORT: string,
    APP_GESTORSHORTS_SOCIALNETWORK_PUT_UPDATESHORT: string,
    APP_GESTORSHORTS_SOCIALNETWORK_DELETE_DELETESHORT: string,
    APP_GESTORSHORTS_SOCIALNETWORK_GET_SEARCHSHORT: string,
    APP_GESTORSHORTS_SOCIALNETWORK_GETSHORTSBYDESCRIPTION_GET: string,
    DB_HOST:string,
    DB_PORT:number,
    DB_NAME:string,
    DB_USER:string,
    DB_PASSWORD:string,
    JWT_PRIVATEKEY: string
}

let structure: data = {...require('../../../../../conf/config_socialnetwork_ambienteesc.json')}

export default structure;